# -*- coding: utf-8 -*-
"""phase2_gradient

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10oQ5ZRoHdj5lsZJnS4DIDG5EmB7Seicq
"""

import numpy as np
import matplotlib

# Permet de sauvegarder la figure sans l'afficher
matplotlib.use('Agg')

import matplotlib.pyplot as plt

# Données d'entraînement
X = np.array([
    [0.2, 0.1],
    [0.8, 0.9],
    [0.3, 0.7],
    [0.9, 0.2]
])

# Étiquettes attendues
y = np.array([0, 1, 1, 0])


# Fonction sigmoïde
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# Calcul de la Binary Cross-Entropy
def compute_loss(y_true, y_pred):
    # Évite log(0)
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)

    return -np.mean(
        y_true * np.log(y_pred) +
        (1 - y_true) * np.log(1 - y_pred)
    )


# Initialisation aléatoire des poids
np.random.seed(42)

w = np.random.randn(2) * 0.01
b = 0.0

learning_rate = 0.1
n_epochs = 50

# Liste qui stocke la loss de chaque époque
losses = []

for epoch in range(n_epochs):

    # ----------------------------
    # Forward pass
    # ----------------------------

    # Somme pondérée
    z = np.dot(X, w) + b

    # Prédictions du neurone
    y_pred = sigmoid(z)

    # Calcul de la loss
    loss = compute_loss(y, y_pred)

    # On garde la loss pour tracer la courbe
    losses.append(loss)

    # ----------------------------
    # Backpropagation
    # ----------------------------

    # Erreur entre la prédiction et la vraie valeur
    error = y_pred - y

    # Gradient des poids
    dw = np.dot(X.T, error) / len(X)

    # Gradient du biais
    db = np.mean(error)

    # ----------------------------
    # Mise à jour des paramètres
    # ----------------------------

    w = w - learning_rate * dw
    b = b - learning_rate * db

    # Affichage tous les 10 epochs
    if epoch % 10 == 0:
        print(f"Epoch {epoch:3d} | Loss: {loss:.4f} | w: {w.round(3)} | b: {b:.3f}")


# ----------------------------
# Courbe de la loss
# ----------------------------

plt.figure(figsize=(8, 4))
plt.plot(losses)

plt.xlabel("Epoch")
plt.ylabel("Loss BCE")
plt.title("Convergence du neurone unique")

plt.savefig("phase2_loss_curve.png", dpi=100, bbox_inches="tight")

print("\nCourbe sauvegardée : phase2_loss_curve.png")
print(f"Loss finale : {losses[-1]:.4f}")

"""Scénario normal

Résultat attendu :

La loss diminue progressivement à chaque epoch.
La loss finale est plus faible que la loss initiale.
La courbe est décroissante, ce qui montre que la descente de gradient fonctionne correctement.

Commentaire :

Les poids sont mis à jour à chaque itération grâce au gradient calculé. Le modèle apprend progressivement et améliore ses prédictions, ce qui explique la diminution de la loss.

italicized text

---
Cas limite (learning_rate = 0)

learning_rate = 0

Résultat attendu :

Les poids ne changent jamais. La loss reste identique pendant les 50 epochs. La courbe est horizontale.

Commentaire :

Avec un taux d'apprentissage nul, aucune mise à jour des paramètres n'est effectuée. Le modèle n'apprend donc rien et la loss reste constante.


---

Scénario adversarial (learning_rate = 10.0)

learning_rate = 10.0

Résultat attendu :

La loss augmente fortement ou oscille. Les poids prennent des valeurs très grandes. Le modèle ne converge plus.

Commentaire :

Un taux d'apprentissage trop élevé provoque des mises à jour trop importantes. Le modèle dépasse constamment le minimum recherché et la loss devient instable.
"""