# -*- coding: utf-8 -*-
"""phase1_neurone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6uMaF7-ZHheM8vWqWwX51FJ5U5xEBew
"""

import numpy as np
print(np.__version__) # doit afficher 1.x ou 2.x, pas une erreur

import numpy as np

# Vérifie que NumPy est bien installé
print(np.__version__)

# Données d'entrée (4 points avec 2 caractéristiques)
X = np.array([
    [0.2, 0.1],
    [0.8, 0.9],
    [0.3, 0.7],
    [0.9, 0.2],
])

# Les bonnes réponses (classes)
y = np.array([0, 1, 1, 0])

# Fonction sigmoïde : transforme une valeur en probabilité entre 0 et 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Calcule la sortie du neurone
def forward(X, w, b):
    # Somme pondérée + biais
    z = np.dot(X, w) + b

    # On applique la fonction sigmoïde
    return sigmoid(z)

# Calcule l'erreur avec la Binary Cross-Entropy
def compute_loss(y_true, y_pred):
    # Évite les problèmes avec log(0)
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)

    # Formule de la BCE
    loss = -np.mean(
        y_true * np.log(y_pred) +
        (1 - y_true) * np.log(1 - y_pred)
    )

    return loss

# Poids choisis à la main (pas d'entraînement pour l'instant)
w = np.array([0.5, -0.3])
b = 0.1

# Calcul des prédictions
y_pred = forward(X, w, b)

# Calcul de l'erreur
loss = compute_loss(y, y_pred)

# Affichage des résultats
print("Prédictions :", y_pred.round(3))
print("Loss :", round(loss, 3))

# Scénario normal

# Poids donnés dans l'énoncé
w = np.array([0.5, -0.3])
b = 0.1

# Calcul des prédictions
y_pred = forward(X, w, b)

# Calcul de la loss
loss = compute_loss(y, y_pred)

print("=== Scénario normal ===")
print("Prédictions :", y_pred.round(3))
print("Loss :", round(loss, 3))

# Remarque :
# Avec ces poids fixés, la loss est d'environ 0.706.
# Elle n'est pas inférieure à 0.4 car les poids n'ont pas été entraînés.
# Une meilleure valeur sera obtenue après la phase d'entraînement.

# ==========================
# Cas limite
# ==========================

# Toutes les entrées valent 0
X_zero = np.zeros((4, 2))

# Le neurone ne reçoit aucune information des entrées.
# La sortie dépend uniquement du biais.
y_pred_zero = forward(X_zero, w, b)

print("\n=== Cas limite ===")
print("Prédictions :", y_pred_zero.round(3))

# Toutes les valeurs doivent être identiques
# car sigmoid(0 + b) = sigmoid(b).

# ==========================
# Scénario adversarial
# ==========================

# Tous les poids et le biais sont initialisés à 0
w = np.zeros(2)
b = 0

# Calcul des prédictions
y_pred_adv = forward(X, w, b)

# Calcul de la loss
loss_adv = compute_loss(y, y_pred_adv)

print("\n=== Scénario adversarial ===")
print("Prédictions :", y_pred_adv.round(3))
print("Loss :", round(loss_adv, 3))

# Avec des poids nuls, la somme pondérée vaut toujours 0.
# sigmoid(0) = 0.5 pour tous les exemples.
# Le neurone ne fait donc aucune distinction entre les classes.
# La loss obtenue est proche de 0.693, ce qui correspond au pire point de départ.